name: Zber pocasia
on:
  schedule:
    - cron: '0 * * * *' # Spustí sa každú hodinu
  workflow_dispatch: # Umožňuje spustiť skript ručne tlačidlom

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Dôležité: povoľuje zapisovať späť do repozitára
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        run: python main.py
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data.csv
          git commit -m "Aktualizácia dát o počasí"
          git push
